---


  - name: Install MySQL
    apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
    with_items:
    - python-mysqldb
    - mysql-server
    when: ansible_os_family == "Debian"

  - name: Install MySQL
    yum: name={{ item }} state=present
    with_items:
    - MySQL-python
    - mariadb-server
    when: ansible_os_family == "RedHat"




  - name: Start the MySQL service
    service:
      name: mysql
      state: started
      enabled: true
    when: ansible_os_family == "Debian"

  - name: Start the MySQL service
    service:
      name: mariadb
      state: started
      enabled: true
    when: ansible_os_family == "RedHat"


  - name: Create mysql database
    mysql_db: name={{ wp_mysql_db }} state=present

  - name: Create mysql user
    mysql_user: 
      name={{ wp_mysql_user }} 
      password={{ wp_mysql_password }} 
      priv=*.*:ALL
