---



- name: "remove the old directories "
  file:
     path: /var/www/html/magento
     state: absent


- name: Ubuntu | Configure Virtualhost
  template:
    src=httpd.conf.j2
    dest=/etc/apache2/sites-enabled/{{ domain }}.conf
  when: ansible_os_family == "Debian"

- name: RedHat | Configure Virtualhost
  template:
    src=httpdcentos.conf.j2
    dest=/etc/httpd/conf.d/{{ domain }}.conf
  when: ansible_os_family == "RedHat"





- name: Download Source
  get_url: 
    url=https://github.com/magento/magento2/archive/2.2.2.zip
    dest=/tmp/magento.zip
    validate_certs=no 



- name: Extract Source
  become: yes
  unarchive: src=/tmp/magento.zip dest=/var/www/html/ copy=no


- name: rename directory to magento
  command: mv /var/www/html/magento2-2.2.2 /var/www/html/magento



- name: "Change file ownership, group and mode"
  shell: find /var/www/html/magento -type d -exec chmod 0755 {} \; && find /var/www/html/magento -type f -exec chmod 0644 {} \; && chown -R www-data:www-data /var/www/html/magento
  when: ansible_os_family == "Debian"


- name: "Change file ownership, group and mode"
  shell: find /var/www/html/magento -type d -exec chmod 0755 {} \; && find /var/www/html/magento -type f -exec chmod 0644 {} \; && chown -R apache:apache /var/www/html/magento
  when: ansible_os_family == "RedHat"





- name: "change dir ownership"
  file:
      path: /var/www/html/magento
      owner: www-data
      group: www-data
      mode: 0755
      state: directory
      recurse: no
  when: ansible_os_family == "Debian"
  notify:
    - restart apache2




- name: "change dir ownership"
  file:
      path: /var/www/html/magento
      owner: apache
      group: apache
      mode: 0755
      state: directory
      recurse: no
  when: ansible_os_family == "RedHat"
  notify:
    - restart apache2




- name: Create a new database
  mysql_db:
    name: 'magentodb'
    login_password: '{{ mysql_root_passwd }}'
    state: present


- name: Create a new database user
  mysql_user:
    name: 'magentodbusr'
    password: '123456789'
    login_password: '{{ mysql_root_passwd }}'
    priv: 'magentodb.*:ALL'
    state: present



- name: install composer
  yum: 
    name: composer
    state: latest
  when: ansible_os_family == "RedHat"


- name: install composer
  apt:
    name: composer
    state: latest
  when: ansible_os_family == "Debian"

- name: install autoload
  shell: composer install
  args:
    chdir: /var/www/html/magento

- name: Update magento config file
  template:
    src: local.xml.j2
    dest: /var/www/html/magento/app/etc/local.xml
    owner: apache
    group: apache
  notify:
    - restart httpd
  when: ansible_os_family == "RedHat"


- name: Update magneto config file
  template:
    src: local.xml.j2
    dest: /var/www/html/magento/app/etc/local.xml
    owner: www-data
    group: www-data
  notify:
    - restart apache2
  when: ansible_os_family == "Debian"

- name: install magento
  shell: php /var/www/html/magento/bin/magento setup:install --base-url=http://{{ domain }}  --db-host=localhost --db-name=magentodb --db-user=magentodbusr --db-password=123456789 --admin-firstname=Magento --admin-lastname=User --admin-email=admin@{{ domain }} --admin-user=admin --admin-password= '{{ magento_passwd }}' --backend-frontname=admin --language=en_US --currency=USD --timezone=Africa/Cairo --use-rewrites=1


- name: "Change file ownership, group and mode"
  shell: find /var/www/html/magento -type d -exec chmod 0755 {} \; && find /var/www/html/magento -type f -exec chmod 0644 {} \; && chown -R www-data:www-data /var/www/html/magento
  when: ansible_os_family == "Debian"


- name: "Change file ownership, group and mode"
  shell: find /var/www/html/magento -type d -exec chmod 0755 {} \; && find /var/www/html/magento -type f -exec chmod 0644 {} \; && chown -R apache:apache /var/www/html/magento
  when: ansible_os_family == "RedHat"





- name: "change dir ownership"
  file:
      path: /var/www/html/magento
      owner: www-data
      group: www-data
      mode: 0770
      state: directory
      recurse: no
  when: ansible_os_family == "Debian"
  notify:
    - restart apache2




- name: "change dir ownership"
  file:
      path: /var/www/html/magento
      owner: apache
      group: apache
      mode: 0770
      state: directory
      recurse: no
  when: ansible_os_family == "RedHat"
  notify:
    - restart apache2

- name: Update system local file
  template:
    src: locale.gen.j2
    dest: /etc/local.gen
    owner: root
    group: root
  notify:
    - update locale
  when: ansible_os_family == "Debian"



#- name: install static content
#  shell: php /var/www/html/magento/bin/magento setup:static-content:deploy -f
#  notify:
#    - restart apache2
#  when: ansible_os_family == "Debian"
