
---
- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: restart apache2
  service: name=apache2 state=restarted enabled=yes

- name: restart httpd
  service: name=httpd state=restarted enabled=yes



