---
- name: install epel Repo
  yum: name=epel-release state=present
  when: ansible_os_family == "RedHat"


- name: "Install Common pacakges from CentOS mirror"
  yum: state=latest name={{ item }}
  with_items:
  - libselinux-python
  - unzip
  - wget
  - tar
  - epel-release
  - tcpdump
  - unzip
  when: ansible_os_family == "RedHat"








- name: "Install Common pacakges for Ubuntu"
  apt: state=latest name={{ item }} update_cache=yes
  with_items:
  - sudo
  - vim
  - unzip
  - wget
  - tar
  - unzip
  when: ansible_os_family == "Debian"



