


- name: copy hostname to bareos-dir
  copy:
    src: /home/hostvar.yml
    dest: /tmp/hostvar.yml
    mode: 0744
    force: yes

- name: get client hostname
  command: cat /tmp/hostvar.yml
  register: client_name


- name: debug variable
  debug:
    var: client_name

- name: copy conf to bareos-dir
  copy:
    src: /home/bareosfd.conf
    dest: /tmp/bareosfd.conf
    mode: 0744
    force: yes



- name: Checking if it is already added
  shell: grep {{ client_name }}.stdout /etc/bareos/bareos-dir.conf
  ignore_errors: yes
  register: grep_result



- name: if not added append conf to bareos-dir.conf
  shell: cat /tmp/bareosfd.conf >> /etc/bareos/bareos-dir.conf
  when: grep_result.stdout == ""


