---


- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  when: ansible_os_family == "Debian"


- name: "remove the old directories "
  file:
     path: /var/www/html/wordpress
     state: absent



- name: Ubuntu | Configure Virtualhost
  template:
    src=httpd.conf.j2
    dest=/etc/apache2/sites-enabled/{{ domain }}.conf
  when: ansible_os_family == "Debian"

- name: RedHat | Configure Virtualhost
  template:
    src=httpdcentos.conf.j2
    dest=/etc/httpd/conf.d/{{ domain }}.conf
  when: ansible_os_family == "RedHat"




- name: "Create Directory "
  file:
     path: /var/www/html/wordpress
     state: directory



- name: Download WordPress
  get_url: 
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/wordpress.tar.gz
    validate_certs=no 



- name: Extract Wordpress
  become: yes
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/html/ copy=no


- name: "Change file ownership, group and mode"
  shell: find /var/www/html/wordpress -type d -exec chmod 0755 {} \; && find /var/www/html/wordpress -type f -exec chmod 0644 {} \; && chown -R www-data:www-data /var/www/html/wordpress
  when: ansible_os_family == "Debian"


- name: "Change file ownership, group and mode"
  shell: find /var/www/html/wordpress -type d -exec chmod 0755 {} \; && find /var/www/html/wordpress -type f -exec chmod 0644 {} \; && chown -R apache:apache /var/www/html/wordpress
  when: ansible_os_family == "RedHat"





- name: "change dir ownership"
  file:
      path: /var/www/html/wordpress
      owner: www-data
      group: www-data
      mode: 0755
      state: directory
      recurse: no
  when: ansible_os_family == "Debian"
  notify:
    - restart apache2




- name: "change dir ownership"
  file:
      path: /var/www/html/wordpress
      owner: apache
      group: apache
      mode: 0755
      state: directory
      recurse: no
  when: ansible_os_family == "RedHat"
  notify:
    - restart httpd




- name: Create a new database
  mysql_db:
    name: wpdb
    login_password: '{{ mysql_root_passwd }}'
    state: present
- name: Create a new database user
  mysql_user:
    name: wpdbusr
    password: 123456789
    login_password: '{{ mysql_root_passwd }}'
    priv: 'wpdb.*:ALL'
    state: present





- name: Update WordPress config file
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
    owner: apache
    group: apache
  notify:
    - restart httpd
  when: ansible_os_family == "RedHat"


- name: Update WordPress config file
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
    owner: www-data
    group: www-data
  notify:
    - restart apache2
  when: ansible_os_family == "Debian"

- include: phpmyadmin.yml
- include: ftpuser.yml
- include: firewall.yml
#- include: ssl.yml

