---




- name: copy mysql repo
  copy:
    src: mysql-community-release-el7-5.noarch.rpm
    dest: /home/mysql-community-release-el7-5.noarch.rpm
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == "RedHat"

- name: Installing webstatic repo
  yum:
    name: /home/mysql-community-release-el7-5.noarch.rpm
    state: present
  when: ansible_os_family == "RedHat"


- name: Install MySQL
  apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
  with_items:
  - python-mysqldb
  - mysql-server
  when: ansible_os_family == "Debian"

- name: Install MySQL
  yum: name={{ item }} state=present
  with_items:
  - MySQL-python
  - mysql-server
  when: ansible_os_family == "RedHat"




- name: Start the MySQL service
  service: 
    name: mysql 
    state: started
    enabled: true
  when: ansible_os_family == "Debian"

- name: Start the MySQL service
  service:
    name: mysqld
    state: started
    enabled: true
  when: ansible_os_family == "RedHat"




- name: update mysql root password for all root accounts
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql_root_passwd }}"
    login_user: root
    login_password: "{{ mysql_root_passwd }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost 
