---
#
# Installing Java 8
#
# Add the Java ppa repository
- name: Define java_packages.
  set_fact:
    java_packages: " java-1.7.0-openjdk | list "
  when: java_packages is not defined


- name: Add Java repository
  apt_repository:
   repo: ppa:webupd8team/java
  when: ansible_os_family == 'Debian'

# Automatically accepts the Oracle License popup in the terminal
- name: Automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
  when: ansible_os_family == 'Debian'

- name: Ensure Java is installed.
  package: "name={{ item }} state=installed"
  with_items: java-1.7.0-openjdk
  when: ansible_os_family == 'RedHat'

# Install Java 8

- name: Install the Java 8 package
  apt:
   name: oracle-java8-installer
   state: present
   update_cache: yes
  when: ansible_os_family == 'Debian'
#- name: Install the Java 8 package
#  yum:
#   name: oracle-java8-installer
#   state: present
#  update_cache: yes
#  when: ansible_os_family == 'RedHat'
#- include: redhat-java.yml
 # when: ansible_os_family == 'RedHat'




