---
# csf/tasks/main.yml

- name: include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "main.yml"
  tags:
    - csf
    - vars
    - packages

- import_tasks: disable_firewall.yml
  tags:
    - csf

- import_tasks: install.yml
  tags:
    - csf

- import_tasks: configure.yml
  tags:
    - csf

- name: ensure csf/lfd started/enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - csf
    - lfd
  tags:
    - csf
    - services
